# Generated by Django 5.2 on 2025-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='profile_pictures')),
            ],
        ),
    ]
